spring:
  application:
    name: Project_4
  
  datasource:
    url: jdbc:mysql://localhost:3306/projek_perpus?serverTimezone=Asia/Jakarta
    username: root          # Sesuaikan dengan user database Anda
    password:               # Sesuaikan dengan password database Anda
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # 'update' akan menyesuaikan schema tanpa menghapus data
    show-sql: true          # Menampilkan query SQL di console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect